name: Update Pfaedle files OCTranspo

on:
  workflow_call:

jobs:
  upload-release-asset:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.13.1'

      - name: Install GTFS tidy
        run: |
          go install github.com/patrickbr/gtfstidy@latest
          gtfstidy --help

      - name: Download unzip and zip
        run: sudo apt install unzip zip

      - name: Install OSM tools
        run: sudo apt install osmium-tool osmctools

      - name: Build Pfaedle
        run: |
          if ! command -v pfaedle &> /dev/null; then
            git clone --recurse-submodules https://github.com/ad-freiburg/pfaedle
            cd pfaedle
            mkdir build && cd build
            cmake ..
            make -j
            sudo make install
            cd ..
          else
            echo "Pfaedle is already installed."
          fi

      - name: Download osm file
        run: |
          wget https://download.geofabrik.de/north-america/canada/ontario-latest.osm.pbf

      - name: Download OCTranspo GTFS
        id: download_oct_gtfs
        run: |
          wget "https://oct-gtfs-emasagcnfmcgeham.z01.azurefd.net/public-access/GTFSExport.zip" -O octranspo_gtfs.zip
          echo "OC_GTFS_FILE=octranspo_gtfs.zip" >> $GITHUB_OUTPUT

      - name: Calculate OCTranspo GTFS MD5 Hash
        id: calculate_oct_gtfs_md5
        run: |
          filepath="${{ steps.download_oct_gtfs.outputs.OC_GTFS_FILE }}"
          md5_hash=$(md5sum "$filepath" | awk '{print $1}')
          echo "OC_GTFS_MD5=$md5_hash" >> $GITHUB_OUTPUT
          echo "OC_GTFS_MD5_FILE=$filepath.md5" >> $GITHUB_OUTPUT
          echo "$md5_hash" > "$filepath.md5"

      - name: Download Existing OCTranspo GTFS MD5 Hash
        id: download_existing_oct_gtfs_md5
        run: |
          ASSET_NAME="${{ steps.download_oct_gtfs.outputs.OC_GTFS_FILE }}"
          MD5_ASSET_NAME="${ASSET_NAME}.md5"
          RELEASE_TAG="latest"
          RELEASE_URL="https://github.com/${{ github.repository }}/releases/download/${RELEASE_TAG}/${MD5_ASSET_NAME}"
          if wget --spider --quiet "$RELEASE_URL"; then
            echo "OC_GTFS_MD5_EXISTS=true" >> $GITHUB_OUTPUT
            wget --quiet -O existing_oct_gtfs_md5.txt "$RELEASE_URL"
            EXISTING_OC_GTFS_MD5=$(cat existing_oct_gtfs_md5.txt)
            echo "EXISTING_OC_GTFS_MD5=$EXISTING_OC_GTFS_MD5" >> $GITHUB_OUTPUT
          else
            echo "OC_GTFS_MD5_EXISTS=false" >> $GITHUB_OUTPUT
          fi

      - name: Run Pfaedle and Zip (Conditional)
        if: steps.download_existing_oct_gtfs_md5.outputs.OC_GTFS_MD5_EXISTS == 'false' || steps.calculate_oct_gtfs_md5.outputs.OC_GTFS_MD5 != steps.download_existing_oct_gtfs_md5.outputs.EXISTING_OC_GTFS_MD5
        id: run_pfaedle_zip
        run: |
          # Unzip OCTranspo GTFS
          unzip octranspo_gtfs.zip -d octranspo_gtfs
          rm octranspo_gtfs.zip

          cp octranspo_gtfs/stop_times.txt stop_times_backup.txt

          # Run Pfaedle OCTranspo network
          # We use the combined filter OSM and combine all MOTs into one run
          pfaedle -x ontario-latest.osm.pbf octranspo_gtfs -F --inplace --mots bus,trolley-bus,trolleybus,trolley,ferry,rail,metro,subway,tram,streetcar --write-colors --drop-shapes true

          echo 'move stop times back from the backup'
          mv stop_times_backup.txt octranspo_gtfs/stop_times.txt

          echo 'gtfs tidy running'
          
          # This command (head) removes the last line from shapes.txt
          head -n -1 octranspo_gtfs/shapes.txt > octranspo_gtfs/shapes.txt.tmp; mv octranspo_gtfs/shapes.txt.tmp octranspo_gtfs/shapes.txt

          # gtfstidy --fix --drop-errs -o octranspo_gtfs_tidy/ octranspo_gtfs/

          echo 'zipping...'

          # Zip octranspo gtfs
          (cd octranspo_gtfs && zip -r -9 ../octranspo_gtfs_pfaedle.zip .)

      - name: Upload Assets OCTranspo GTFS
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ github.token }}
          ASSET_PATH: octranspo_gtfs_pfaedle.zip
          MD5_ASSET_PATH: ${{ steps.calculate_oct_gtfs_md5.outputs.OC_GTFS_MD5_FILE }}
          RELEASE_TAG: latest
        run: |
          NEW_MD5="${{ steps.calculate_oct_gtfs_md5.outputs.OC_GTFS_MD5 }}"
          MD5_EXISTS="${{ steps.download_existing_oct_gtfs_md5.outputs.OC_GTFS_MD5_EXISTS }}"
          EXISTING_MD5="${{ steps.download_existing_oct_gtfs_md5.outputs.EXISTING_OC_GTFS_MD5 }}"
          PFAEDLE_STEP_SUCCESS="${{ steps.run_pfaedle_zip.outcome == 'success' }}"

          if [[ "$MD5_EXISTS" == "false" ]]; then
            echo "No existing MD5 found for OCTranspo GTFS. Uploading both file and MD5."
            if [[ -f "$ASSET_PATH" && "$PFAEDLE_STEP_SUCCESS" == "true" ]]; then
              gh release upload "$RELEASE_TAG" "$ASSET_PATH" --clobber
            else
              echo "Pfaedle and zip step was skipped or failed, not uploading main asset."
            fi
            gh release upload "$RELEASE_TAG" "$MD5_ASSET_PATH" --clobber
          elif [[ "$NEW_MD5" != "$EXISTING_MD5" ]]; then
            echo "Existing MD5 for OCTranspo GTFS is different. Uploading both file and new MD5."
            if [[ -f "$ASSET_PATH" && "$PFAEDLE_STEP_SUCCESS" == "true" ]]; then
              gh release upload "$RELEASE_TAG" "$ASSET_PATH" --clobber
            else
              echo "Pfaedle and zip step was skipped or failed, not uploading main asset."
            fi
            gh release upload "$RELEASE_TAG" "$MD5_ASSET_PATH" --clobber
          else
            echo "Existing MD5 for OCTranspo GTFS matches the new MD5. Skipping upload."
          fi
        shell: bash
